name: searchable_paginated_dropdown
description: Flutter searchable dropdown widget which can be used also with paginated requests.
version: 1.3.0
homepage: https://github.com/mdikcinar/searchable_dropdown

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ">=2.8.2 <3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  better_linter:
    git:
      url: git@github.com:mdikcinar/better_linter.git
      ref: master
  flutter_test:
    sdk: flutter